#! /bin/bash
# Copyright 2014 Cumulus Networks, Inc. All rights reserved.
# Author: David Sinn, dsinn@cumulusnetworks.com
# https://github.com/CumulusNetworks/customer-scripts/blob/master/01-manage-if-addrs
#
#       This file is used in the following:
#       Knowledge Base: https://support.cumulusnetworks.com/hc/en-us/articles/202971633-Deploying-VRRP-on-Cumulus-Linux
#
#
# $1 - interface name
# $2 - up or down

TMPFILE=/tmp/ifplugd.$1.tmp

case $2 in
        down)   ip addr flush dev $1
                kill $(cat /var/run/vrrpd_${1}_*.pid)
                ;;
        up)     ifquery $1 > $TMPFILE
                ip addr add $(sed -n "s/^\s*address//p" $TMPFILE) dev $1
                vrrpd $(sed -n "s/^\s*up vrrpd//p" $TMPFILE)
                rm -f $TMPFILE
                ;;
esac

exit 0
