#!/bin/bash 
CP='cp -a  --parents '
DEST='/mnt/persist/'


SAVE="
/root/ 
/home/ 
/etc/ssh/ 
/etc/network/inferfaces.d/ 
/etc/network/interfaces 
/etc/quagga/Quagga.conf 
/etc/quagga/daemons 
/etc/quagga/vtysh.conf 
/etc/cumulus/ports.conf
/etc/default/clagd  
/etc/default/isc-dhcp-relay
/etc/apt/sources.list.d/bdd.list 
/etc/apt/apt.conf 
/etc/monit/monitrc 
/etc/snmp/snmp.conf 
/etc/sudoers 
/etc/resolv.conf 
/etc/hostname 
/etc/hosts
/etc/group 
/etc/passwd 
/etc/shadow 
"

for foo in "$SAVE"
do
$CP -a $foo $DEST
done

tree $DEST

echo "#-----------------------------------------------------------------------"
echo "  You will forget /mnt/persist and it wil HURT
echo "  run  /root/bin/fix-persist after reboot to remove files
echo "#-----------------------------------------------------------------------"
