#!/bin/bash 
# Copyright 2014 Cumulus Networks, Inc. All rights reserved.

CP='cp -a  --parents '
DEST='/mnt/persist/'


SAVE="
/root/ 
/home/ 
/etc/ssh/ 
/etc/netns/
/etc/network/interfaces.d/ 
/etc/rc.local
/etc/network/interfaces 
/etc/quagga/Quagga.conf 
/etc/quagga/daemons 
/etc/quagga/vtysh.conf 
/etc/cumulus/ports.conf
/etc/default/isc-dhcp-relay
/etc/apt/sources.list.d/support.list
/etc/sudoers 
/etc/resolv.conf 
/etc/hostname 
/etc/hosts
/etc/group 
/etc/passwd 
/etc/shadow 
/etc/default/openvswitch-vtep
/usr/share/openvswitch/scripts/ovs-ctl-vtep
"

for foo in "$SAVE"
do
$CP -a $foo $DEST
done

tree $DEST

echo "#-----------------------------------------------------------------------"
echo "  You will forget /mnt/persist and it wil HURT
echo "  run  /root/bin/fix-persist after reboot to remove files
echo "#-----------------------------------------------------------------------"
