#!/bin/bash
# Copyright 2014 Cumulus Networks, Inc. All rights reserved.


/bin/rm -rf /mnt/persist/*
/bin/mkdir -p /mnt/persist/etc/cumulus
/bin/cp -af /etc/cumulus/.license* /mnt/persist/etc/cumulus/
/usr/bin/tree /mnt/persist/
